# Configuration file for song history uploader

import os

# An array of song history database files as stored in EasyWorship
songhistory_db_paths = [
    "C:\\Users\\Public\\Documents\\Softouch\\EasyWorship\\Default\\v6.1\\Databases\\Data\\SongHistory.db"
]
# A working directory for the song history uploader
songhistory_base_path = os.path.expandvars("%LOCALAPPDATA%\\EasyWorshipSongHistory\\")
# The CSV file generated by the song history uploader
songhistory_csv_path = songhistory_base_path + "SongHistory.csv"
# A file containing a set of song title prefixes that will be ignored
song_prefixes_path = songhistory_base_path + "prefixes_to_ignore.txt"
# Path to the log file
log_path = songhistory_base_path + "log.txt"
# The URL for upload of the song history
upload_url = "http://s3-eu-west-1.amazonaws.com/ccaworship/SongHistory.csv"
